FROM node:current-alpine AS development
ENV NODE_ENV development

# Create app directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Install app dependencies
COPY package.json pnpm-lock.yaml ./

RUN pnpm install

# Bundle app source
COPY . .

# Expose port 3333
EXPOSE 3333

# Start the app
CMD [ "pnpm", "run", "dev" ]