# Generated by Django 4.2 on 2023-04-13 01:35

from django.db import migrations


def populate_products(apps, schema_editor):
    Product = apps.get_model('app', 'Product')
    Product.objects.create(name='Reebook Club C 85 Pump', price=129.99, stock=10,
                           image_url='https://media.hypedc.com/cdn-cgi/image/width=1200,format=avif/products/6f10a890/gw4793_wht_01.jpg')
    Product.objects.create(name='Nike Air Max 97', price=199.99, stock=10,
                           image_url='https://media.hypedc.com/cdn-cgi/image/width=1200,format=avif/products/460f1897/921826-101_wht_01.jpg')
    Product.objects.create(name='Nike Air Max 90', price=159.99, stock=10,
                           image_url='https://media.hypedc.com/cdn-cgi/image/width=1200,format=avif/products/460f1897/921826-101_wht_01.jpg')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_products),
    ]
